# Generated by Django 3.2.16 on 2022-11-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('art_content', models.TextField(verbose_name='Текст статьи')),
                ('karera_1', models.CharField(blank=True, max_length=200, verbose_name='Первый шаг в карьерной лестнице')),
                ('karera_2', models.CharField(blank=True, max_length=200, verbose_name='Второй шаг в карьерной лестнице')),
                ('karera_3', models.CharField(blank=True, max_length=200, verbose_name='Третий шаг в карьерной лестнице')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
                ('vk', models.CharField(max_length=200, verbose_name='Ссылка на страницут в ВК')),
                ('ok', models.CharField(max_length=200, verbose_name='Ссылка на страницут в Однокласниках')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='География человека')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название партии')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300, verbose_name='Текст коментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('name_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.ManyToManyField(related_name='City', to='main.City'),
        ),
        migrations.AddField(
            model_name='article',
            name='party',
            field=models.ManyToManyField(related_name='Article', to='main.Party'),
        ),
    ]
