# Generated by Django 4.1.2 on 2022-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название партии')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='karera_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Первый шаг в карьерной лестнице'),
        ),
        migrations.AlterField(
            model_name='article',
            name='karera_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Второй шаг в карьерной лестнице'),
        ),
        migrations.AlterField(
            model_name='article',
            name='karera_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Третий шаг в карьерной лестнице'),
        ),
        migrations.AddField(
            model_name='article',
            name='party',
            field=models.ManyToManyField(related_name='Article', to='main.party'),
        ),
    ]
