# Generated by Django 4.1.3 on 2022-11-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('preview', models.TextField(verbose_name='Превью текст')),
                ('author', models.CharField(max_length=200, verbose_name='Автор статьи')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
                ('tags', models.ManyToManyField(related_name='Article', to='newsposts.tags')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
